from __future__ import annotations

from datetime import datetime, timedelta, timezone
from typing import Any

from .config import CHENGDU_DESTINATION


def utc_now_datetime() -> datetime:
    return datetime.now(timezone.utc)


def iso_hours_ago(base: datetime, hours: float) -> str:
    return (base - timedelta(hours=hours)).isoformat(timespec="seconds").replace("+00:00", "Z")


def short_bucket(base: datetime, hours_ago: int) -> str:
    date = base - timedelta(hours=hours_ago)
    return date.strftime("%m-%d %H:00")


def create_event(base: datetime, source: str, host: str, event: dict[str, Any]) -> dict[str, Any]:
    payload = dict(event)
    hours_ago = float(payload.pop("hoursAgo"))
    if source != "sample":
        payload["id"] = f"{source}-{payload['id']}"
    payload["timestamp"] = iso_hours_ago(base, hours_ago)
    payload["source"] = source
    payload["host"] = host
    payload["raw"] = {
        "source": source,
        "destination": CHENGDU_DESTINATION,
        "rayId": payload.get("rayId", ""),
        "matchedRules": payload.get("ruleMatches", []),
        "cloudflareAction": payload.get("action", "allow"),
    }
    return payload


def create_sample_events(
    now: datetime | None = None,
    *,
    source: str = "sample",
    host: str = "r0l1dehome.asia",
) -> list[dict[str, Any]]:
    base = now or utc_now_datetime()
    events = [
        {
            "id": "evt-1009",
            "hoursAgo": 0.35,
            "clientIp": "185.220.101.42",
            "country": "德国",
            "region": "Hesse",
            "city": "Frankfurt",
            "latitude": 50.1109,
            "longitude": 8.6821,
            "locationPrecision": "city",
            "asn": "AS24940",
            "method": "GET",
            "path": "/.env",
            "statusCode": 403,
            "userAgent": "curl/8.2 security scanner",
            "rayId": "8fc1a21d4e12c901",
            "action": "block",
            "ruleId": "builtin-sensitive-path",
            "ruleName": "敏感路径探测",
            "eventType": "敏感路径探测",
            "riskLevel": "critical",
            "confidence": 0.96,
            "summary": "来源 IP 请求 .env 并被 Cloudflare 拦截。",
            "ruleMatches": ["路径命中 .env", "Cloudflare block", "扫描器 User-Agent"],
        },
        {
            "id": "evt-1008",
            "hoursAgo": 0.9,
            "clientIp": "45.61.139.18",
            "country": "美国",
            "region": "California",
            "city": "San Jose",
            "latitude": 37.3387,
            "longitude": -121.8853,
            "locationPrecision": "city",
            "asn": "AS53667",
            "method": "POST",
            "path": "/api/search",
            "query": "q=' OR 1=1--",
            "statusCode": 403,
            "userAgent": "Mozilla/5.0",
            "rayId": "8fc1a1b25aa244db",
            "action": "managed_challenge",
            "ruleId": "builtin-sqli",
            "ruleName": "疑似 SQL 注入",
            "eventType": "疑似注入",
            "riskLevel": "high",
            "confidence": 0.88,
            "summary": "查询参数包含典型 SQL 注入片段，已触发挑战。",
            "ruleMatches": ["SQL 关键词", "POST 请求", "Cloudflare managed_challenge"],
        },
        {
            "id": "evt-1007",
            "hoursAgo": 1.6,
            "clientIp": "103.253.144.19",
            "country": "新加坡",
            "region": "Central",
            "city": "Singapore",
            "latitude": 1.3521,
            "longitude": 103.8198,
            "locationPrecision": "city",
            "asn": "AS45102",
            "method": "GET",
            "path": "/wp-login.php",
            "statusCode": 404,
            "userAgent": "Mozilla/5.0 zgrab/0.x",
            "rayId": "8fc19f753e24a8ae",
            "action": "challenge",
            "ruleId": "builtin-wp-probe",
            "ruleName": "WordPress 探测",
            "eventType": "目录探测",
            "riskLevel": "high",
            "confidence": 0.91,
            "summary": "非 WordPress 站点出现 wp-login.php 探测请求。",
            "ruleMatches": ["敏感路径 wp-login.php", "可疑 User-Agent"],
        },
        {
            "id": "evt-1006",
            "hoursAgo": 2.25,
            "clientIp": "91.219.237.21",
            "country": "俄罗斯",
            "region": "Moscow",
            "city": "Moscow",
            "latitude": 55.7558,
            "longitude": 37.6173,
            "locationPrecision": "region",
            "asn": "AS197695",
            "method": "GET",
            "path": "/admin",
            "statusCode": 403,
            "userAgent": "python-requests/2.31",
            "rayId": "8fc19d62d093ed27",
            "action": "block",
            "ruleId": "builtin-admin-probe",
            "ruleName": "后台路径探测",
            "eventType": "恶意扫描",
            "riskLevel": "high",
            "confidence": 0.84,
            "summary": "后台路径被连续探测，Cloudflare 已执行 block。",
            "ruleMatches": ["路径 /admin", "Cloudflare block"],
        },
        {
            "id": "evt-1005",
            "hoursAgo": 3.1,
            "clientIp": "203.0.113.84",
            "country": "日本",
            "region": "Tokyo",
            "city": "Tokyo",
            "latitude": 35.6762,
            "longitude": 139.6503,
            "locationPrecision": "city",
            "asn": "AS2516",
            "method": "GET",
            "path": "/posts/first",
            "statusCode": 200,
            "userAgent": "Mozilla/5.0 AppleWebKit/537.36",
            "rayId": "8fc199b671da441a",
            "action": "allow",
            "ruleId": "traffic-normal",
            "ruleName": "普通访问",
            "eventType": "正常访问",
            "riskLevel": "info",
            "confidence": 0.64,
            "summary": "公开文章访问，请求行为正常。",
            "ruleMatches": ["缓存命中", "状态码 200"],
        },
        {
            "id": "evt-1004",
            "hoursAgo": 4.4,
            "clientIp": "152.32.210.77",
            "country": "中国香港",
            "region": "Hong Kong",
            "city": "Hong Kong",
            "latitude": 22.3193,
            "longitude": 114.1694,
            "locationPrecision": "city",
            "asn": "AS135377",
            "method": "GET",
            "path": "/phpmyadmin/index.php",
            "statusCode": 404,
            "userAgent": "Go-http-client/1.1",
            "rayId": "8fc194d73b128eee",
            "action": "challenge",
            "ruleId": "builtin-sensitive-path",
            "ruleName": "敏感路径探测",
            "eventType": "敏感路径探测",
            "riskLevel": "high",
            "confidence": 0.9,
            "summary": "phpMyAdmin 路径探测触发挑战。",
            "ruleMatches": ["路径 phpmyadmin", "可疑 User-Agent"],
        },
        {
            "id": "evt-1003",
            "hoursAgo": 5.2,
            "clientIp": "198.51.100.21",
            "country": "荷兰",
            "region": "North Holland",
            "city": "Amsterdam",
            "latitude": 52.3676,
            "longitude": 4.9041,
            "locationPrecision": "country",
            "asn": "AS60781",
            "method": "GET",
            "path": "/api/comment",
            "query": "content=<script>alert(1)</script>",
            "statusCode": 403,
            "userAgent": "Mozilla/5.0",
            "rayId": "8fc1915c01924409",
            "action": "managed_challenge",
            "ruleId": "builtin-xss",
            "ruleName": "疑似 XSS",
            "eventType": "疑似 XSS",
            "riskLevel": "medium",
            "confidence": 0.79,
            "summary": "评论接口参数包含 script 片段，已触发托管挑战。",
            "ruleMatches": ["XSS 关键词", "Cloudflare managed_challenge"],
        },
        {
            "id": "evt-1002",
            "hoursAgo": 8.4,
            "clientIp": "200.160.2.3",
            "country": "巴西",
            "region": "Sao Paulo",
            "city": "Sao Paulo",
            "latitude": -23.5505,
            "longitude": -46.6333,
            "locationPrecision": "estimated",
            "asn": "AS22548",
            "method": "GET",
            "path": "/rss.xml",
            "statusCode": 200,
            "userAgent": "FeedFetcher-Google",
            "rayId": "8fc17921704dcb3a",
            "action": "allow",
            "ruleId": "crawler-known",
            "ruleName": "已知爬虫",
            "eventType": "爬虫访问",
            "riskLevel": "low",
            "confidence": 0.58,
            "summary": "订阅抓取行为，暂不构成威胁。",
            "ruleMatches": ["已知爬虫 User-Agent"],
        },
        {
            "id": "evt-1001",
            "hoursAgo": 12.2,
            "clientIp": "203.0.113.210",
            "country": "韩国",
            "region": "Seoul",
            "city": "Seoul",
            "latitude": 37.5665,
            "longitude": 126.978,
            "locationPrecision": "city",
            "asn": "AS4766",
            "method": "HEAD",
            "path": "/",
            "statusCode": 200,
            "userAgent": "UptimeRobot/2.0",
            "rayId": "8fc151b28076f1b7",
            "action": "allow",
            "ruleId": "monitor-normal",
            "ruleName": "可用性检测",
            "eventType": "正常访问",
            "riskLevel": "info",
            "confidence": 0.7,
            "summary": "站点可用性探测，请求正常。",
            "ruleMatches": ["HEAD 请求", "状态码 200"],
        },
    ]
    return [create_event(base, source, host, event) for event in events]


def create_sample_traffic_trend(now: datetime | None = None) -> list[dict[str, Any]]:
    base = now or utc_now_datetime()
    return [
        {"label": short_bucket(base, 21), "requests": 760, "threats": 18, "blocked": 9, "bandwidthMb": 86, "cachedPercent": 84, "originMb": 14},
        {"label": short_bucket(base, 18), "requests": 690, "threats": 15, "blocked": 8, "bandwidthMb": 72, "cachedPercent": 81, "originMb": 13},
        {"label": short_bucket(base, 15), "requests": 820, "threats": 24, "blocked": 15, "bandwidthMb": 94, "cachedPercent": 83, "originMb": 16},
        {"label": short_bucket(base, 12), "requests": 930, "threats": 31, "blocked": 18, "bandwidthMb": 111, "cachedPercent": 79, "originMb": 23},
        {"label": short_bucket(base, 9), "requests": 880, "threats": 27, "blocked": 14, "bandwidthMb": 104, "cachedPercent": 82, "originMb": 19},
        {"label": short_bucket(base, 6), "requests": 1012, "threats": 44, "blocked": 24, "bandwidthMb": 128, "cachedPercent": 77, "originMb": 30},
        {"label": short_bucket(base, 3), "requests": 1160, "threats": 57, "blocked": 31, "bandwidthMb": 143, "cachedPercent": 74, "originMb": 37},
        {"label": short_bucket(base, 0), "requests": 1084, "threats": 49, "blocked": 29, "bandwidthMb": 136, "cachedPercent": 78, "originMb": 30},
    ]
